### ISSUE TITLE
First active datafile is not restored from remote when missing

### ISSUE THREAD

**Issue by OmarElawady** [rivine/0-db#121]
After creating a namespace and adding enough data to commit a datafile, I removed the datafile (but kept the indexes) and restarted the zdb. The "active" datafile is created from scratch and reads are performed on it rather than fetching it from remote by calling the hook. Other datafiles are queried when they are needed correctly

A workaround:
```patch
diff --git a/bin/.keep b/bin/.keep
deleted file mode 100644
index e69de29..0000000
diff --git a/libzdb/data.c b/libzdb/data.c
index bcd6a9d..df79fad 100644
--- a/libzdb/data.c
+++ b/libzdb/data.c
@@ -242,8 +242,11 @@ static inline void data_release_dataid(data_root_t *root, fileid_t dataid, int f
 //
 void data_initialize(char *filename, data_root_t *root) {
     int fd;
+    if ((fd = open(filename, O_RDWR, 0600)) < 0) {
+        data_open_notfound_hook(filename);
+    }
 
-    if((fd = open(filename, O_CREAT | O_RDWR, 0600)) < 0) {
+    if(fd == -1 && (fd = open(filename, O_CREAT | O_RDWR, 0600)) < 0) {
         // ignoring initializer on read-only filesystem
         if(errno == EROFS)
             return;
```

**Comment by maxux** [comment]
After investigation and some discussion with @OmarElawady, this was the expected behavior.
This happen with an inconsistant index.

Last index/data needs to be available on zdb start, which was not the case.
