### ISSUE TITLE
WORM mode per namespace

### ISSUE THREAD

**Issue by gmachtel** [rivine/0-db#61]
# Detailed description
'Write only Read multiple' mode per namespace 
No history per key, so cannot delete/modify a key/val

**Comment by maxux** [comment]
This should be quite easy to implement, maximum 1d should be enough
It's just a mode where you cannot overwrite nor delete a key, basically ?

**Comment by maxux** [comment]
This should be working using `development-worm` branch.
This will need to be re-applied on `development-lib` staging branch.
