### ISSUE TITLE
Caching mode

### ISSUE THREAD

**Issue by gmachtel** [rivine/0-db#63]
# Detailed description
If block is no longer there, the ZDB asks 3bot (Redis) for retrieving the block

**Comment by maxux** [comment]
This is not difficult to implement but require some thinking. My idea from the beginning was avoiding any client-side code inside 0-db, but it seems this is less and less possible.

The idea would then to have client-side code inside 0-db, and this could then be used to implement this feature and be used by replication stuff (by event-driven pushing changes inside slaves)

This could require some time, like multiple days to ensure everything works fine

**Comment by maxux** [comment]
The issue #89 will fix this in another way.
