### ISSUE TITLE
Building on Mac10.11.6 gives an error

### ISSUE THREAD

**Issue by serboctor** [rivine/0-db#73]
![zdb error ](https://user-images.githubusercontent.com/6323012/70917202-955cff00-2025-11ea-95dc-28f94ec9a92f.png)

**Comment by maxux** [comment]
Please pull and tell me if it's fixed for you.
Warning and compilation error are fixed by https://github.com/threefoldtech/0-db/commit/dd49f923d69005450f94b4884c490fd560160e63 and https://github.com/threefoldtech/0-db/commit/92d9313c15a96f084a4ed0d288749c42ca192183

**Comment by RafyAmgadBenjamin** [comment]
I have tested it again and I am getting this error now
![image](https://user-images.githubusercontent.com/46320202/70983260-187f6300-20c1-11ea-8bf9-f212df4ce6e7.png)

**Comment by maxux** [comment]
It's really annoying to support old system... I fix that.

**Comment by maxux** [comment]
Can you try since https://github.com/threefoldtech/0-db/commit/0b7b7076eb93cb28fb1cce3e383970d5711885fd ?

**Comment by maxux** [comment]
What's up about this ?

**Comment by RafyAmgadBenjamin** [comment]
After updating to ```Catalina OS``` version 10.15.2 it is working
