### ISSUE TITLE
health: keep track of number of write issue and time of last error on the namespace info

### ISSUE THREAD

**Issue by muhamadazmy** [rivine/0-db#75]
We need a way to check the health of zdb. As discussed, the best way to implement this is that NSINFO should also return the number of "write errors" and the time of last error

**Comment by maxux** [comment]
In verification: last 0-db development include this feature.

**Comment by zaibon** [comment]
@muhamadazmy after you did some test with it. We will need to define a way to upgrade the 0-db container on all the nodes in the field.
